using System.Text;
using BlazeCard.Models;
using Passbook.Generator;
using Passbook.Generator.Fields;

namespace BlazeCard.Services;

public class ApplePassService : IApplePassService
{
    public string GenerateCodeSnippet(CardModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by BlazeCard — paste into your backend that uses dotnet-passbook");
        sb.AppendLine("// https://github.com/tomasmcguinness/dotnet-passbook");
        sb.AppendLine();
        sb.AppendLine("using Passbook.Generator;");
        sb.AppendLine("using Passbook.Generator.Fields;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Security.Cryptography.X509Certificates;");
        sb.AppendLine();
        sb.AppendLine("var passGenerator = new PassGenerator();");
        sb.AppendLine("var request = new PassGeneratorRequest");
        sb.AppendLine("{");
        sb.AppendLine("    PassTypeIdentifier = \"pass.com.example.yourpass\", // TODO: your Pass Type ID");
        sb.AppendLine("    TeamIdentifier = \"YOURTEAMID\", // TODO: your Apple Team ID");
        sb.AppendLine("    SerialNumber = Guid.NewGuid().ToString(\"N\"), // required; unique per issued pass");
        sb.AppendLine($"    Description = \"{Escape(model.Description)}\",");
        sb.AppendLine($"    OrganizationName = \"{Escape(model.OrganizationName)}\",");
        sb.AppendLine($"    LogoText = \"{Escape(model.LogoText)}\",");
        sb.AppendLine("    Style = PassStyle.Generic,");
        sb.AppendLine($"    BackgroundColor = \"{ToRgb(model.BackgroundColor)}\",");
        sb.AppendLine($"    LabelColor = \"{ToRgb(model.LabelColor)}\",");
        sb.AppendLine($"    ForegroundColor = \"{ToRgb(model.ForegroundColor)}\",");
        if (model.SuppressStripShine)
            sb.AppendLine("    SuppressStripShine = true, // only strip display flag; Wallet still cover-crops, no stretch");
        sb.AppendLine("};");
        sb.AppendLine();

        foreach (var f in model.HeaderFields)
            sb.AppendLine(FieldCall("AddHeaderField", f));
        foreach (var f in model.PrimaryFields)
            sb.AppendLine(FieldCall("AddPrimaryField", f));
        foreach (var f in model.SecondaryFields)
            sb.AppendLine(FieldCall("AddSecondaryField", f));
        foreach (var f in model.AuxiliaryFields)
            sb.AppendLine(FieldCall("AddAuxiliaryField", f));
        foreach (var f in model.BackFields)
            sb.AppendLine(FieldCall("AddBackField", f));

        if (model.BarcodeFormat != BarcodeFormat.None)
        {
            sb.AppendLine();
            sb.AppendLine($"request.AddBarcode(BarcodeType.{MapBarcode(model.BarcodeFormat)}, \"{Escape(model.BarcodeMessage)}\", \"ISO-8859-1\", \"{Escape(model.BarcodeAltText)}\");");
        }

        AppendImagePlaceholders(sb, model);

        sb.AppendLine();
        sb.AppendLine("// Certificates — Final tab uses an unsigned preview package by default.");
        sb.AppendLine("// Integrators: load Apple Pass Type ID + WWDR certs before Generate() for Wallet installs.");
        sb.AppendLine("// request.PassbookCertificate = new X509Certificate2(\"path/to/pass.p12\", \"cert-password\");");
        sb.AppendLine("// request.AppleWWDRCACertificate = new X509Certificate2(\"path/to/AppleWWDRCA.cer\");");
        sb.AppendLine();
        sb.AppendLine("byte[] pkpassBytes = passGenerator.Generate(request);");
        sb.AppendLine("File.WriteAllBytes(\"membership.pkpass\", pkpassBytes);");

        return sb.ToString();
    }

    public bool TryParseCodeSnippet(string code, CardModel target, out string? warning)
    {
        warning = null;
        if (string.IsNullOrWhiteSpace(code))
        {
            warning = "Apple code snippet is empty.";
            return false;
        }

        var description = ExtractQuotedAssignment(code, "Description");
        var organization = ExtractQuotedAssignment(code, "OrganizationName");
        var logoText = ExtractQuotedAssignment(code, "LogoText");

        if (description is null && organization is null && logoText is null
            && !code.Contains("AddPrimaryField", StringComparison.Ordinal)
            && !code.Contains("AddHeaderField", StringComparison.Ordinal))
        {
            warning = "Could not parse Apple code snippet.";
            return false;
        }

        if (description is not null) target.Description = description;
        if (organization is not null) target.OrganizationName = organization;
        if (logoText is not null) target.LogoText = logoText;
        target.SuppressStripShine = code.Contains("SuppressStripShine = true", StringComparison.Ordinal);

        TryParseFields(code, "AddHeaderField", target.HeaderFields);
        TryParseFields(code, "AddPrimaryField", target.PrimaryFields);
        TryParseFields(code, "AddSecondaryField", target.SecondaryFields);
        TryParseFields(code, "AddAuxiliaryField", target.AuxiliaryFields);
        TryParseFields(code, "AddBackField", target.BackFields);

        return true;
    }

    private static void TryParseFields(string code, string method, List<PassField> target)
    {
        var fields = new List<PassField>();
        var needle = method + "(new StandardField(";
        var idx = 0;
        while (true)
        {
            var start = code.IndexOf(needle, idx, StringComparison.Ordinal);
            if (start < 0) break;
            start += needle.Length;
            var end = FindMatchingCloseParen(code, start - 1);
            if (end < 0) break;
            var args = code[start..end];
            var parts = SplitQuotedArgs(args);
            if (parts.Count >= 3)
            {
                var field = new PassField
                {
                    Key = parts[0],
                    Label = parts[1],
                    Value = parts[2],
                    TextAlignment = ParseAlignment(code, end)
                };
                fields.Add(field);
            }
            idx = end + 1;
        }

        if (fields.Count > 0)
        {
            target.Clear();
            target.AddRange(fields);
        }
    }

    private static int FindMatchingCloseParen(string code, int openParenIndex)
    {
        var depth = 0;
        var inString = false;
        for (var i = openParenIndex; i < code.Length; i++)
        {
            var c = code[i];
            if (inString)
            {
                if (c == '\\' && i + 1 < code.Length) { i++; continue; }
                if (c == '"') inString = false;
                continue;
            }
            if (c == '"') { inString = true; continue; }
            if (c == '(') depth++;
            else if (c == ')')
            {
                depth--;
                if (depth == 0) return i;
            }
        }
        return -1;
    }

    private static TextAlignment ParseAlignment(string code, int ctorCloseParen)
    {
        var sliceEnd = Math.Min(code.Length, ctorCloseParen + 80);
        var slice = code[ctorCloseParen..sliceEnd];
        if (slice.Contains("PKTextAlignmentCenter", StringComparison.Ordinal)) return TextAlignment.Center;
        if (slice.Contains("PKTextAlignmentRight", StringComparison.Ordinal)) return TextAlignment.Right;
        if (slice.Contains("PKTextAlignmentNatural", StringComparison.Ordinal)) return TextAlignment.Natural;
        return TextAlignment.Left;
    }

    private static List<string> SplitQuotedArgs(string args)
    {
        var result = new List<string>();
        var i = 0;
        while (i < args.Length)
        {
            while (i < args.Length && (args[i] == ',' || char.IsWhiteSpace(args[i]))) i++;
            if (i >= args.Length) break;
            if (args[i] != '"') break;
            i++;
            var sb = new StringBuilder();
            while (i < args.Length && args[i] != '"')
            {
                if (args[i] == '\\' && i + 1 < args.Length)
                {
                    sb.Append(args[i + 1]);
                    i += 2;
                    continue;
                }
                sb.Append(args[i]);
                i++;
            }
            if (i < args.Length && args[i] == '"') i++;
            result.Add(sb.ToString());
        }
        return result;
    }

    private static string? ExtractQuotedAssignment(string code, string property)
    {
        var token = property + " = \"";
        var start = code.IndexOf(token, StringComparison.Ordinal);
        if (start < 0) return null;
        start += token.Length;
        var end = code.IndexOf('"', start);
        if (end < 0) return null;
        return Unescape(code[start..end]);
    }

    private static void AppendImagePlaceholders(StringBuilder sb, CardModel model)
    {
        var hasIcon = model.PassbookImages.Keys.Any(k =>
            k is PassbookImage.Icon or PassbookImage.Icon2X or PassbookImage.Icon3X);
        var hasStrip = model.PassbookImages.Keys.Any(k =>
            k is PassbookImage.Strip or PassbookImage.Strip2X or PassbookImage.Strip3X);

        if (hasStrip)
        {
            sb.AppendLine();
            sb.AppendLine("// Strip: Wallet cover-crops to a fixed slot (no stretch in pass.json / dotnet-passbook).");
            sb.AppendLine("// PassStyle.Generic ignores strip.png on device; Coupon / StoreCard / EventTicket show it.");
        }

        if (!hasIcon)
        {
            sb.AppendLine();
            sb.AppendLine("// Apple requires icon.png (usually also @2x / @3x) in a real .pkpass bundle.");
            sb.AppendLine("// request.Images.Add(PassbookImage.Icon2X, File.ReadAllBytes(\"path/to/icon@2x.png\"));");
        }

        if (model.PassbookImages.Count == 0)
            return;

        sb.AppendLine();
        sb.AppendLine("// Images — PassbookImage slots (see Passbook.Generator.PassbookImage)");
        foreach (var key in model.PassbookImages.Keys.OrderBy(k => k.ToString()))
        {
            var file = key.ToFilename();
            sb.AppendLine($"request.Images.Add(PassbookImage.{key}, File.ReadAllBytes(\"path/to/{file}\"));");
        }
    }

    private static string FieldCall(string method, PassField field)
    {
        var ctor = $"new StandardField(\"{Escape(field.Key)}\", \"{Escape(field.Label)}\", \"{Escape(field.Value)}\")";
        var align = MapAlignment(field.TextAlignment);
        if (align is not null)
            ctor += $" {{ TextAlignment = FieldTextAlignment.{align} }}";
        return $"request.{method}({ctor});";
    }

    private static string? MapAlignment(TextAlignment alignment) => alignment switch
    {
        TextAlignment.Center => nameof(FieldTextAlignment.PKTextAlignmentCenter),
        TextAlignment.Right => nameof(FieldTextAlignment.PKTextAlignmentRight),
        TextAlignment.Natural => nameof(FieldTextAlignment.PKTextAlignmentNatural),
        _ => null
    };

    private static string MapBarcode(BarcodeFormat format) => format switch
    {
        BarcodeFormat.QR => "PKBarcodeFormatQR",
        BarcodeFormat.PDF417 => "PKBarcodeFormatPDF417",
        BarcodeFormat.Aztec => "PKBarcodeFormatAztec",
        BarcodeFormat.Code128 => "PKBarcodeFormatCode128",
        _ => "PKBarcodeFormatQR"
    };

    private static string ToRgb(string hex)
    {
        if (string.IsNullOrWhiteSpace(hex) || hex.Length < 7 || hex[0] != '#')
            return "rgb(13, 115, 119)";
        var r = Convert.ToInt32(hex[1..3], 16);
        var g = Convert.ToInt32(hex[3..5], 16);
        var b = Convert.ToInt32(hex[5..7], 16);
        return $"rgb({r}, {g}, {b})";
    }

    private static string Escape(string value) =>
        (value ?? string.Empty)
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string Unescape(string value) =>
        value
            .Replace("\\\"", "\"", StringComparison.Ordinal)
            .Replace("\\\\", "\\", StringComparison.Ordinal)
            .Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\r", "\r", StringComparison.Ordinal);
}
