using System.Text;
using BlazeCard.Models;

namespace BlazeCard.Services;

public class ApplePassService : IApplePassService
{
    public string GenerateCodeSnippet(CardModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by BlazeCard — paste into your backend that uses dotnet-passbook");
        sb.AppendLine("// https://github.com/tomasmcguinness/dotnet-passbook");
        sb.AppendLine();
        sb.AppendLine("using Passbook.Generator;");
        sb.AppendLine("using Passbook.Generator.Fields;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Security.Cryptography.X509Certificates;");
        sb.AppendLine();
        sb.AppendLine("var passGenerator = new PassGenerator();");
        sb.AppendLine("var request = new PassGeneratorRequest");
        sb.AppendLine("{");
        sb.AppendLine("    PassTypeIdentifier = \"pass.com.example.yourpass\", // TODO: your Pass Type ID");
        sb.AppendLine("    TeamIdentifier = \"YOURTEAMID\", // TODO: your Apple Team ID");
        sb.AppendLine($"    Description = \"{Escape(model.Description)}\",");
        sb.AppendLine($"    OrganizationName = \"{Escape(model.OrganizationName)}\",");
        sb.AppendLine($"    LogoText = \"{Escape(model.LogoText)}\",");
        sb.AppendLine("    Style = PassStyle.Generic,");
        sb.AppendLine($"    BackgroundColor = \"{ToRgb(model.BackgroundColor)}\",");
        sb.AppendLine($"    LabelColor = \"{ToRgb(model.LabelColor)}\",");
        sb.AppendLine($"    ForegroundColor = \"{ToRgb(model.ForegroundColor)}\",");
        sb.AppendLine("};");
        sb.AppendLine();

        foreach (var f in model.HeaderFields)
            sb.AppendLine($"request.AddHeaderField(new StandardField(\"{Escape(f.Key)}\", \"{Escape(f.Label)}\", \"{Escape(f.Value)}\"));");
        foreach (var f in model.PrimaryFields)
            sb.AppendLine($"request.AddPrimaryField(new StandardField(\"{Escape(f.Key)}\", \"{Escape(f.Label)}\", \"{Escape(f.Value)}\"));");
        foreach (var f in model.SecondaryFields)
            sb.AppendLine($"request.AddSecondaryField(new StandardField(\"{Escape(f.Key)}\", \"{Escape(f.Label)}\", \"{Escape(f.Value)}\"));");
        foreach (var f in model.AuxiliaryFields)
            sb.AppendLine($"request.AddAuxiliaryField(new StandardField(\"{Escape(f.Key)}\", \"{Escape(f.Label)}\", \"{Escape(f.Value)}\"));");
        foreach (var f in model.BackFields)
            sb.AppendLine($"request.AddBackField(new StandardField(\"{Escape(f.Key)}\", \"{Escape(f.Label)}\", \"{Escape(f.Value)}\"));");

        if (model.BarcodeFormat != BarcodeFormat.None)
        {
            sb.AppendLine();
            sb.AppendLine($"request.AddBarcode(BarcodeType.{MapBarcode(model.BarcodeFormat)}, \"{Escape(model.BarcodeMessage)}\", \"ISO-8859-1\", \"{Escape(model.BarcodeAltText)}\");");
        }

        AppendImagePlaceholders(sb, model);

        sb.AppendLine();
        sb.AppendLine("// Certificates — load in your integrator backend (BlazeCard never signs)");
        sb.AppendLine("// request.PassbookCertificate = new X509Certificate2(\"path/to/pass.p12\", \"cert-password\");");
        sb.AppendLine("// request.AppleWWDRCACertificate = new X509Certificate2(\"path/to/AppleWWDRCA.cer\");");
        sb.AppendLine();
        sb.AppendLine("byte[] pkpassBytes = passGenerator.Generate(request);");
        sb.AppendLine("File.WriteAllBytes(\"membership.pkpass\", pkpassBytes);");

        return sb.ToString();
    }

    public bool TryParseCodeSnippet(string code, CardModel target, out string? warning)
    {
        warning = null;
        if (string.IsNullOrWhiteSpace(code))
        {
            warning = "Apple code snippet is empty.";
            return false;
        }

        var description = ExtractQuotedAssignment(code, "Description");
        var organization = ExtractQuotedAssignment(code, "OrganizationName");
        var logoText = ExtractQuotedAssignment(code, "LogoText");

        if (description is null && organization is null && logoText is null
            && !code.Contains("AddPrimaryField", StringComparison.Ordinal)
            && !code.Contains("AddHeaderField", StringComparison.Ordinal))
        {
            warning = "Could not parse Apple code snippet.";
            return false;
        }

        if (description is not null) target.Description = description;
        if (organization is not null) target.OrganizationName = organization;
        if (logoText is not null) target.LogoText = logoText;

        TryParseFields(code, "AddHeaderField", target.HeaderFields);
        TryParseFields(code, "AddPrimaryField", target.PrimaryFields);
        TryParseFields(code, "AddSecondaryField", target.SecondaryFields);
        TryParseFields(code, "AddAuxiliaryField", target.AuxiliaryFields);
        TryParseFields(code, "AddBackField", target.BackFields);

        return true;
    }

    private static void TryParseFields(string code, string method, List<PassField> target)
    {
        var fields = new List<PassField>();
        var needle = method + "(new StandardField(";
        var idx = 0;
        while (true)
        {
            var start = code.IndexOf(needle, idx, StringComparison.Ordinal);
            if (start < 0) break;
            start += needle.Length;
            var end = code.IndexOf("))", start, StringComparison.Ordinal);
            if (end < 0) break;
            var args = code[start..end];
            var parts = SplitQuotedArgs(args);
            if (parts.Count >= 3)
            {
                fields.Add(new PassField
                {
                    Key = parts[0],
                    Label = parts[1],
                    Value = parts[2]
                });
            }
            idx = end + 2;
        }

        if (fields.Count > 0)
        {
            target.Clear();
            target.AddRange(fields);
        }
    }

    private static List<string> SplitQuotedArgs(string args)
    {
        var result = new List<string>();
        var i = 0;
        while (i < args.Length)
        {
            while (i < args.Length && (args[i] == ',' || char.IsWhiteSpace(args[i]))) i++;
            if (i >= args.Length) break;
            if (args[i] != '"') break;
            i++;
            var sb = new StringBuilder();
            while (i < args.Length && args[i] != '"')
            {
                if (args[i] == '\\' && i + 1 < args.Length)
                {
                    sb.Append(args[i + 1]);
                    i += 2;
                    continue;
                }
                sb.Append(args[i]);
                i++;
            }
            if (i < args.Length && args[i] == '"') i++;
            result.Add(sb.ToString());
        }
        return result;
    }

    private static string? ExtractQuotedAssignment(string code, string property)
    {
        var token = property + " = \"";
        var start = code.IndexOf(token, StringComparison.Ordinal);
        if (start < 0) return null;
        start += token.Length;
        var end = code.IndexOf('"', start);
        if (end < 0) return null;
        return Unescape(code[start..end]);
    }

    private static void AppendImagePlaceholders(StringBuilder sb, CardModel model)
    {
        void Add(string? dataUri, string path)
        {
            if (string.IsNullOrEmpty(dataUri)) return;
            sb.AppendLine($"// request.Images.Add(PassbookImage.Logo, File.ReadAllBytes(\"{path}\"));");
        }

        Add(model.LogoImage, "path/to/logo@2x.png");
        Add(model.IconImage, "path/to/icon@2x.png");
        Add(model.StripImage, "path/to/strip@2x.png");
        Add(model.HeroImage, "path/to/hero@2x.png");
        Add(model.ThumbnailImage, "path/to/thumbnail@2x.png");
    }

    private static string MapBarcode(BarcodeFormat format) => format switch
    {
        BarcodeFormat.QR => "PKBarcodeFormatQR",
        BarcodeFormat.PDF417 => "PKBarcodeFormatPDF417",
        BarcodeFormat.Aztec => "PKBarcodeFormatAztec",
        BarcodeFormat.Code128 => "PKBarcodeFormatCode128",
        _ => "PKBarcodeFormatQR"
    };

    private static string ToRgb(string hex)
    {
        if (string.IsNullOrWhiteSpace(hex) || hex.Length < 7 || hex[0] != '#')
            return "rgb(13, 115, 119)";
        var r = Convert.ToInt32(hex[1..3], 16);
        var g = Convert.ToInt32(hex[3..5], 16);
        var b = Convert.ToInt32(hex[5..7], 16);
        return $"rgb({r}, {g}, {b})";
    }

    private static string Escape(string value) =>
        (value ?? string.Empty)
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string Unescape(string value) =>
        value
            .Replace("\\\"", "\"", StringComparison.Ordinal)
            .Replace("\\\\", "\\", StringComparison.Ordinal)
            .Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\r", "\r", StringComparison.Ordinal);
}
