using System.Text.Json;
using BlazeCard.Models.Google;

namespace BlazeCard.Services;

public static class GoogleCodeTemplate
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
    };

    public static string Wrap(GenericObjectDto body)
    {
        var json = JsonSerializer.Serialize(body, JsonOptions);
        return
            """
            // Generated by BlazeCard — Google Wallet Generic Objects API
            // Prerequisites: create a Generic Class, enable Wallet API, obtain an OAuth access token.
            // Replace {ISSUER_ID} and {ACCESS_TOKEN} in your integrator backend.
            // logo is optional — Wallet shows the first letter of cardTitle when omitted.
            // header and cardTitle are required on GenericObject.
            //
            // 1. Insert Generic Class first (object.classId must already exist):
            // POST https://walletobjects.googleapis.com/walletobjects/v1/genericClass
            // { "id": "{ISSUER_ID}.class.sample" }
            //
            // 2. Then insert Generic Object:
            POST https://walletobjects.googleapis.com/walletobjects/v1/genericObject
            Authorization: Bearer {ACCESS_TOKEN}
            Content-Type: application/json

            """
            + json
            + """


            // How to obtain ACCESS_TOKEN — use your Google Cloud service account in your backend.
            // BlazeCard does not call Google APIs and has no Google.Apis.* dependency.
            """;
    }
}
